### ISSUE TITLE
View Category List (3)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-fire-hawks#29]
Given a user selects the "Category Management" from the navbar
When they are directed to `/categories`
Then they should see a list of all categories
And categories should be ordered alphabetically
And each category should have an edit and delete button (functionality for buttons come later) 

FRONTEND

1. Get all categories function/fetch call 
2. Create separate module and element that displays all categories alphabetically
3. Include button to delete in the display
4. Include edit button in the display 

BACKEND

1. create a categories_requests.py
2. create a categories.py
3. Put categories into SQL

**Comment by Matt-Martino** [comment]
Backend support has been completed.  get_all + get_single + create
