### ISSUE TITLE
Login (1)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-fire-hawks#33]
Given a current user is trying to log in
When they submit the login form
Then they should be redirected to the homepage

FRONTEND
1. create login function (pass setToken as arg)
2. create handleLogin function (=onSubmit)
- create GET fetch call for user details (email), foundUsers sets items to local storage and navigate to homepage else invalid login (window.alert)
- set local storage for current value of username and password
- if valid, navigate to homepage
- else (setIsUnsuccessful)
3. create form with the following items:
- username 
- password
- submit button, navigate to homepage
- cancel button, route to register
- if unsuccessful, username or password invalid alert

BACKEND (chuckle)
CREATE Users table with the following 
```
  id int pk
  username varcharacter
  email varcharacter
  firstName varcharacter
  lastName varcharacter
  creationDate datetime
  bio varcharacter
  profileImgUrl varcharacter
  password varcharacter
  active boolean
```

**Comment by swparks040** [comment]
review at your leisure...
