### ISSUE TITLE
Register (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-fire-hawks#34]
Given a user has navigated to the register page and wants to create an account
When they submit the form correctly
Then they should be logged in 
And navigated to the home page

FRONTEND
1. create register function 
2. verify email in database, route to homepage
3. send data to database
4. create GET fetch call to handleRegister, validate email, create user
5. create POST fetch call for registering/creating a new user, navigate to homepage
6. create registration form with following fields:
- firstName (text)
- lastName (text)
- userName (text)
- email (text)
- password (text)
- bio (textarea)
- createdOn (datetime.now())
- submit button (=onSubmit)
- cancel button (=onClick)

BACKEND
-MODELS
1. create users.py Class to accept FRONTEND (exists)
```
Insert into Users (first_name, last_name, username, email, password, bio, created_on, active) values (?, ?, ?, ?, ?, ?, ?, 1)
        """, (
            user['first_name'],
            user['last_name'],
            user['username'],
            user['email'],
            user['password'],
            user['bio'],
            datetime.now()
```
-VIEWS
1. rename users_requests.py for uniformity
2. import as appropriate in class and requestHandler

**Comment by swparks040** [comment]
Review please, Do your worst...
